"use client";

import { useState } from "react";
import type { EquipoOperativoPublico, IntegranteEquipoOperativoPublico, IntegranteHubOperativo, MetricasOperativasHub, ResponsableHub, RolHubOperativo } from "@/lib/data/hubs";

const roles: RolHubOperativo[] = ["Capataz", "Responsable de cuadrilla", "Jardinero", "Ayudante", "Técnico", "Paisajista", "Coordinador", "Otro"];
const vacio = (): IntegranteHubOperativo => ({ id: `hub-operativo-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, nombre: "", email: "", whatsapp: "", rol: "Jardinero", tipoParticipacion: "", activo: true, recibeReportes: true, participaDistribucion: true, porcentajeOCriterio: "", notaInterna: "", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
const integrantePublicoVacio = (): IntegranteEquipoOperativoPublico => ({ nombre: "", rol: "Integrante operativo", activo: true });

type Props = { hubSlug: string; integrantes: IntegranteHubOperativo[]; responsableHub?: ResponsableHub; equipoOperativoPublico?: string | EquipoOperativoPublico; metricasOperativas?: MetricasOperativasHub; clientesActivos: number; trabajosRealizados?: number; ultimaActividad?: string };

function normalizarEquipoPublico(equipo: Props["equipoOperativoPublico"], integrantes: IntegranteHubOperativo[]): EquipoOperativoPublico {
  if (equipo && typeof equipo === "object") return { cantidad: Number(equipo.cantidad || equipo.integrantes.length || 0), integrantes: equipo.integrantes || [] };
  return { cantidad: integrantes.length, integrantes: integrantes.map((integrante) => ({ nombre: integrante.nombre, rol: integrante.rol, activo: integrante.activo })).filter((integrante) => integrante.nombre) };
}

export function HubOperativoEditor({ hubSlug, integrantes, responsableHub, equipoOperativoPublico, metricasOperativas, clientesActivos, trabajosRealizados, ultimaActividad }: Props) {
  const [items, setItems] = useState<IntegranteHubOperativo[]>(integrantes || []);
  const [responsable, setResponsable] = useState<ResponsableHub>(responsableHub || { nombre: "", iniciales: "", rol: "", descripcion: "" });
  const [equipoPublico, setEquipoPublico] = useState<EquipoOperativoPublico>(normalizarEquipoPublico(equipoOperativoPublico, integrantes || []));
  const [metricas, setMetricas] = useState<MetricasOperativasHub>(metricasOperativas || { trabajosTerminados: trabajosRealizados || 0, clientesActivos, ultimaActividad });
  const [estado, setEstado] = useState("El Hub Operativo es el equipo o conjunto de personas que brinda servicio al Hub de demanda.");
  const actualizar = (id: string, cambios: Partial<IntegranteHubOperativo>) => setItems((actuales) => actuales.map((item) => item.id === id ? { ...item, ...cambios } : item));
  const actualizarIntegrantePublico = (index: number, cambios: Partial<IntegranteEquipoOperativoPublico>) => setEquipoPublico((actual) => ({ ...actual, integrantes: actual.integrantes.map((item, itemIndex) => itemIndex === index ? { ...item, ...cambios } : item) }));
  async function guardar() {
    setEstado("Guardando Hub Operativo...");
    const respuesta = await fetch(`/api/hubs/${hubSlug}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hubOperativo: items }) });
    setEstado(respuesta.ok ? "Hub Operativo guardado. Al refrescar se mantiene en la ficha del Hub." : "No se pudo guardar el Hub Operativo.");
  }
  async function guardarPerfilPublico() {
    setEstado("Guardando responsable y métricas públicas...");
    const respuesta = await fetch(`/api/hubs/${hubSlug}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ responsableHub: responsable, equipoOperativoPublico: equipoPublico, metricasOperativas: metricas }) });
    setEstado(respuesta.ok ? "Responsable, equipo público y métricas guardados para la página pública del Hub." : "No se pudo guardar el perfil público del Hub.");
  }
  return <section id="hub-operativo" className="rounded-[2rem] border border-[#d8dfd1] bg-white p-6 shadow-sm">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#7a8a6d]">Hub Operativo</p><h2 className="text-2xl font-black">Equipo que ejecuta el servicio</h2><p className="mt-2 max-w-3xl text-sm font-semibold text-[#66745c]">El Hub de demanda agrupa clientes, vecinos o usuarios. Esta ficha también define quién aparece como responsable en la página pública.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setItems((actuales) => [...actuales, vacio()])} className="rounded-2xl border border-[#cfd8c6] bg-[#f8faf5] px-4 py-3 text-sm font-black">Agregar integrante</button><button type="button" onClick={guardar} className="rounded-2xl bg-[#1f2a1d] px-4 py-3 text-sm font-black text-white">Guardar Hub Operativo</button></div></div>
    <p className="mt-3 text-sm font-black text-[#66745c]">{estado}</p>

    <div className="mt-6 rounded-[1.5rem] border border-[#d8dfd1] bg-[#f8faf5] p-5">
      <div className="flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#7a8a6d]">Página pública del Hub</p><h3 className="text-xl font-black">Responsable, equipo y métricas visibles</h3></div><button type="button" onClick={guardarPerfilPublico} className="rounded-2xl bg-[#1E8F4D] px-4 py-3 text-sm font-black text-white">Guardar datos públicos</button></div>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm font-black">Nombre del responsable<input value={responsable.nombre} onChange={(e) => setResponsable((actual) => ({ ...actual, nombre: e.target.value }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-black">Iniciales del responsable<input value={responsable.iniciales} onChange={(e) => setResponsable((actual) => ({ ...actual, iniciales: e.target.value }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-black">Rol del responsable<input value={responsable.rol} onChange={(e) => setResponsable((actual) => ({ ...actual, rol: e.target.value }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-black">Cantidad de personas del equipo<input type="number" min="0" value={equipoPublico.cantidad} onChange={(e) => setEquipoPublico((actual) => ({ ...actual, cantidad: Number(e.target.value) }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-black md:col-span-2">Descripción del responsable<textarea value={responsable.descripcion} onChange={(e) => setResponsable((actual) => ({ ...actual, descripcion: e.target.value }))} className="mt-1 min-h-24 w-full rounded-xl border p-3" /></label><label className="text-sm font-black">Trabajos terminados<input type="number" min="0" value={metricas.trabajosTerminados} onChange={(e) => setMetricas((actual) => ({ ...actual, trabajosTerminados: Number(e.target.value) }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-black">Clientes activos<input type="number" min="0" value={metricas.clientesActivos} onChange={(e) => setMetricas((actual) => ({ ...actual, clientesActivos: Number(e.target.value) }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-black md:col-span-2">Última actividad<input value={metricas.ultimaActividad || ""} onChange={(e) => setMetricas((actual) => ({ ...actual, ultimaActividad: e.target.value }))} className="mt-1 h-11 w-full rounded-xl border px-3" /></label></div>
      <div className="mt-4 flex items-center justify-between"><h4 className="font-black">Integrantes del equipo operativo público</h4><button type="button" onClick={() => setEquipoPublico((actual) => ({ ...actual, integrantes: [...actual.integrantes, integrantePublicoVacio()] }))} className="rounded-xl border border-[#cfd8c6] bg-white px-3 py-2 text-xs font-black">Agregar integrante público</button></div>
      <div className="mt-3 grid gap-2">{equipoPublico.integrantes.length === 0 ? <p className="rounded-xl bg-white p-3 text-sm font-bold text-[#66745c]">Equipo operativo pendiente de carga.</p> : equipoPublico.integrantes.map((integrante, index) => <div key={index} className="grid gap-2 rounded-xl bg-white p-3 md:grid-cols-[1fr_1fr_auto_auto]"><input value={integrante.nombre} onChange={(e) => actualizarIntegrantePublico(index, { nombre: e.target.value })} placeholder="Nombre" className="h-10 rounded border px-2 font-bold" /><input value={integrante.rol || ""} onChange={(e) => actualizarIntegrantePublico(index, { rol: e.target.value })} placeholder="Rol o tarea" className="h-10 rounded border px-2" /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={integrante.activo !== false} onChange={(e) => actualizarIntegrantePublico(index, { activo: e.target.checked })} /> Activo</label><button type="button" onClick={() => setEquipoPublico((actual) => ({ ...actual, integrantes: actual.integrantes.filter((_, itemIndex) => itemIndex !== index) }))} className="font-black text-[#743c3c]">Quitar</button></div>)}</div>
    </div>

    <div className="mt-5 overflow-x-auto rounded-2xl border border-[#d8dfd1]"><table className="w-full border-collapse text-xs"><thead className="bg-[#f1f4ec] text-left uppercase text-[#66745c]"><tr>{["Nombre", "Email", "WhatsApp", "Rol", "Tipo", "Activo", "Recibe reportes", "Participa distribución", "% / criterio", "Nota", ""].map((h) => <th key={h} className="border p-2">{h}</th>)}</tr></thead><tbody>{items.length === 0 ? <tr><td colSpan={11} className="border p-4 text-center font-bold text-[#66745c]">Todavía no hay integrantes operativos cargados.</td></tr> : items.map((item) => <tr key={item.id} className={item.activo ? "bg-white" : "bg-[#fff7f7]"}><td className="border p-1"><input value={item.nombre} onChange={(e) => actualizar(item.id, { nombre: e.target.value })} className="h-9 min-w-40 rounded border px-2 font-bold" /></td><td className="border p-1"><input value={item.email} onChange={(e) => actualizar(item.id, { email: e.target.value })} className="h-9 min-w-48 rounded border px-2" /></td><td className="border p-1"><input value={item.whatsapp} onChange={(e) => actualizar(item.id, { whatsapp: e.target.value })} className="h-9 min-w-36 rounded border px-2" /></td><td className="border p-1"><select value={item.rol} onChange={(e) => actualizar(item.id, { rol: e.target.value as RolHubOperativo })} className="h-9 min-w-36 rounded border px-2">{roles.map((rol) => <option key={rol}>{rol}</option>)}</select></td><td className="border p-1"><input value={item.tipoParticipacion} onChange={(e) => actualizar(item.id, { tipoParticipacion: e.target.value })} className="h-9 min-w-40 rounded border px-2" /></td><td className="border p-1 text-center"><input type="checkbox" checked={item.activo} onChange={(e) => actualizar(item.id, { activo: e.target.checked })} /></td><td className="border p-1 text-center"><input type="checkbox" checked={item.recibeReportes} onChange={(e) => actualizar(item.id, { recibeReportes: e.target.checked })} /></td><td className="border p-1 text-center"><input type="checkbox" checked={item.participaDistribucion} onChange={(e) => actualizar(item.id, { participaDistribucion: e.target.checked })} /></td><td className="border p-1"><input value={item.porcentajeOCriterio} onChange={(e) => actualizar(item.id, { porcentajeOCriterio: e.target.value })} className="h-9 min-w-32 rounded border px-2" /></td><td className="border p-1"><input value={item.notaInterna} onChange={(e) => actualizar(item.id, { notaInterna: e.target.value })} className="h-9 min-w-48 rounded border px-2" /></td><td className="border p-1 text-center"><button type="button" onClick={() => setItems((actuales) => actuales.filter((actual) => actual.id !== item.id))} className="font-black text-[#743c3c]">×</button></td></tr>)}</tbody></table></div>
  </section>;
}
