"use client";

import { useState } from "react";
import type { IntegranteHubOperativo, RolHubOperativo } from "@/lib/data/hubs";

const roles: RolHubOperativo[] = ["Capataz", "Responsable de cuadrilla", "Jardinero", "Ayudante", "Técnico", "Paisajista", "Coordinador", "Otro"];
const vacio = (): IntegranteHubOperativo => ({ id: `hub-operativo-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, nombre: "", email: "", whatsapp: "", rol: "Jardinero", tipoParticipacion: "", activo: true, recibeReportes: true, participaDistribucion: true, porcentajeOCriterio: "", notaInterna: "", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });

export function HubOperativoEditor({ hubSlug, integrantes }: { hubSlug: string; integrantes: IntegranteHubOperativo[] }) {
  const [items, setItems] = useState<IntegranteHubOperativo[]>(integrantes || []);
  const [estado, setEstado] = useState("El Hub Operativo es el equipo o conjunto de personas que brinda servicio al Hub de demanda.");
  const actualizar = (id: string, cambios: Partial<IntegranteHubOperativo>) => setItems((actuales) => actuales.map((item) => item.id === id ? { ...item, ...cambios } : item));
  async function guardar() {
    setEstado("Guardando Hub Operativo...");
    const respuesta = await fetch(`/api/hubs/${hubSlug}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hubOperativo: items }) });
    setEstado(respuesta.ok ? "Hub Operativo guardado. Al refrescar se mantiene en la ficha del Hub." : "No se pudo guardar el Hub Operativo.");
  }
  return <section id="hub-operativo" className="rounded-[2rem] border border-[#d8dfd1] bg-white p-6 shadow-sm">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#7a8a6d]">Hub Operativo</p><h2 className="text-2xl font-black">Equipo que ejecuta el servicio</h2><p className="mt-2 max-w-3xl text-sm font-semibold text-[#66745c]">El Hub de demanda agrupa clientes, vecinos o usuarios. El Hub Operativo agrupa jardineros, ayudantes, capataz, responsables, técnicos, paisajistas y coordinadores.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setItems((actuales) => [...actuales, vacio()])} className="rounded-2xl border border-[#cfd8c6] bg-[#f8faf5] px-4 py-3 text-sm font-black">Agregar integrante</button><button type="button" onClick={guardar} className="rounded-2xl bg-[#1f2a1d] px-4 py-3 text-sm font-black text-white">Guardar Hub Operativo</button></div></div>
    <p className="mt-3 text-sm font-black text-[#66745c]">{estado}</p>
    <div className="mt-5 overflow-x-auto rounded-2xl border border-[#d8dfd1]"><table className="w-full border-collapse text-xs"><thead className="bg-[#f1f4ec] text-left uppercase text-[#66745c]"><tr>{["Nombre", "Email", "WhatsApp", "Rol", "Tipo", "Activo", "Recibe reportes", "Participa distribución", "% / criterio", "Nota", ""].map((h) => <th key={h} className="border p-2">{h}</th>)}</tr></thead><tbody>{items.length === 0 ? <tr><td colSpan={11} className="border p-4 text-center font-bold text-[#66745c]">Todavía no hay integrantes operativos cargados.</td></tr> : items.map((item) => <tr key={item.id} className={item.activo ? "bg-white" : "bg-[#fff7f7]"}><td className="border p-1"><input value={item.nombre} onChange={(e) => actualizar(item.id, { nombre: e.target.value })} className="h-9 min-w-40 rounded border px-2 font-bold" /></td><td className="border p-1"><input value={item.email} onChange={(e) => actualizar(item.id, { email: e.target.value })} className="h-9 min-w-48 rounded border px-2" /></td><td className="border p-1"><input value={item.whatsapp} onChange={(e) => actualizar(item.id, { whatsapp: e.target.value })} className="h-9 min-w-36 rounded border px-2" /></td><td className="border p-1"><select value={item.rol} onChange={(e) => actualizar(item.id, { rol: e.target.value as RolHubOperativo })} className="h-9 min-w-36 rounded border px-2">{roles.map((rol) => <option key={rol}>{rol}</option>)}</select></td><td className="border p-1"><input value={item.tipoParticipacion} onChange={(e) => actualizar(item.id, { tipoParticipacion: e.target.value })} className="h-9 min-w-40 rounded border px-2" /></td><td className="border p-1 text-center"><input type="checkbox" checked={item.activo} onChange={(e) => actualizar(item.id, { activo: e.target.checked })} /></td><td className="border p-1 text-center"><input type="checkbox" checked={item.recibeReportes} onChange={(e) => actualizar(item.id, { recibeReportes: e.target.checked })} /></td><td className="border p-1 text-center"><input type="checkbox" checked={item.participaDistribucion} onChange={(e) => actualizar(item.id, { participaDistribucion: e.target.checked })} /></td><td className="border p-1"><input value={item.porcentajeOCriterio} onChange={(e) => actualizar(item.id, { porcentajeOCriterio: e.target.value })} className="h-9 min-w-32 rounded border px-2" /></td><td className="border p-1"><input value={item.notaInterna} onChange={(e) => actualizar(item.id, { notaInterna: e.target.value })} className="h-9 min-w-48 rounded border px-2" /></td><td className="border p-1 text-center"><button type="button" onClick={() => setItems((actuales) => actuales.filter((actual) => actual.id !== item.id))} className="font-black text-[#743c3c]">×</button></td></tr>)}</tbody></table></div>
  </section>;
}
