import type { Cliente, Hub } from "@/lib/data/hubs";
import type { ParameterResponse } from "@/lib/data/parameterResponses";

const fecha = (valor?: string) => valor ? new Date(valor).toLocaleString("es-AR") : "—";
const nombreContacto = (contactos: Cliente[], id: string) => contactos.find((c) => c.id === id)?.nombre || "Contacto sin nombre";
const valor = (r: ParameterResponse, v: string | number | undefined) => r.currentValueType === "percent" ? `${v ?? "—"}%` : String(v ?? "—");

export function HubParameterSuggestions({ hub, contactos, respuestas }: { hub: Hub; contactos: Cliente[]; respuestas: ParameterResponse[] }) {
  const grupos = Array.from(respuestas.reduce((mapa, r) => {
    const grupo = mapa.get(r.parameterKey) || { label: r.parameterLabel, currentValue: r.currentValue, currentValueType: r.currentValueType, respuestas: [] as ParameterResponse[] };
    grupo.respuestas.push(r);
    mapa.set(r.parameterKey, grupo);
    return mapa;
  }, new Map<string, { label: string; currentValue: string | number; currentValueType: string; respuestas: ParameterResponse[] }>()).entries());

  return <section className="rounded-[2rem] border border-[#d8dfd1] bg-white p-6 shadow-sm"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#66745c]">Parámetros operativos</p><h2 className="text-2xl font-black">Sugerencias de parámetros</h2><p className="text-sm font-semibold text-[#66745c]">El cliente sugiere. El sistema registra. El operador decide. Estas respuestas no cambian automáticamente los parámetros del Hub.</p></div><a href={`/operativo/hubs/${hub.slug}/parametros`} className="rounded-xl border border-[#cfd8c6] px-4 py-2 text-xs font-black">Editar parámetro del Hub</a></div>{grupos.length === 0 ? <p className="mt-4 rounded-2xl bg-[#f8faf5] p-5 text-sm font-bold text-[#66745c]">Todavía no hay sugerencias de parámetros para este Hub.</p> : <div className="mt-5 grid gap-4">{grupos.map(([key, grupo]) => { const concretas = grupo.respuestas.filter((r) => r.responseType === "sugerir_otro_valor" && r.suggestedValue); const conteoValores = Array.from(concretas.reduce((mapa, r) => mapa.set(String(r.suggestedValue), (mapa.get(String(r.suggestedValue)) || 0) + 1), new Map<string, number>()).entries()); return <article key={key} className="rounded-2xl border border-[#cfd8c6] bg-[#f8faf5] p-4"><h3 className="text-lg font-black">{grupo.label}</h3><p className="text-sm font-bold text-[#66745c]">Valor actual: {grupo.currentValueType === "percent" ? `${grupo.currentValue}%` : grupo.currentValue}</p><div className="mt-3 grid gap-2 text-sm md:grid-cols-4"><p>Confirmaron: <strong>{grupo.respuestas.filter((r) => r.responseType === "confirmar_valor").length}</strong></p><p>Sugirieron subir: <strong>{grupo.respuestas.filter((r) => r.responseType === "sugerir_subir").length}</strong></p><p>Sugirieron bajar: <strong>{grupo.respuestas.filter((r) => r.responseType === "sugerir_bajar").length}</strong></p><p>Otro valor: <strong>{concretas.length}</strong></p></div>{conteoValores.length > 0 && <div className="mt-3 rounded-xl bg-white p-3 text-sm"><p className="font-black">Valores sugeridos concretos</p>{conteoValores.map(([v, cantidad]) => <p key={v}>{valor(grupo.respuestas[0], v)} — {cantidad} persona{cantidad === 1 ? "" : "s"}</p>)}</div>}<div className="mt-3 grid gap-2">{grupo.respuestas.map((r) => <div key={r.id} className="rounded-xl bg-white p-3 text-xs font-semibold"><p className="font-black">{nombreContacto(contactos, r.contactId)} · {fecha(r.createdAt)} · {r.responseType.replaceAll("_", " ")}</p>{r.suggestedValue && <p>Valor sugerido: {valor(r, r.suggestedValue)}</p>}{r.comment && <p>Comentario: {r.comment}</p>}<p>Reporte: {r.reportId} · Estado: {r.status}</p></div>)}</div></article>; })}</div>}</section>;
}
