"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import type { HubPublico, ModuloOperativoHub, ParametrosJardinerosYaHub, RangoComisionManejoPersonal, RangoTrasladoBonoFinalizacion } from "@/lib/data/hubs";

const comisionManejoPersonalInicial: RangoComisionManejoPersonal[] = [
  { desde: 1, hasta: 1, porcentaje: 15 },
  { desde: 2, hasta: 2, porcentaje: 20 },
  { desde: 3, hasta: 5, porcentaje: 25 },
];
const trasladoBonoFinalizacionInicial: RangoTrasladoBonoFinalizacion[] = [
  { desde: 1, hasta: 1, valor: 0 },
  { desde: 2, hasta: 3, valor: 0 },
  { desde: 4, hasta: 6, valor: 0 },
];
const parametrosVacios: ParametrosJardinerosYaHub = { valorHoraTrabajo: 0, comisionResponsableCuadrillaPorcentaje: 0, comisionManejoPersonal: comisionManejoPersonalInicial, traslado: 0, trasladoBonoFinalizacion: trasladoBonoFinalizacionInicial, aceite: 0, nafta: 0, valorHoraCortadoraCesped: 0, valorHoraBordeadora: 0, valorHoraMaquinaEmpuje: 0, mostrarEnWebPublica: false };

function normalizarParametrosJardinerosYa(input?: Partial<ParametrosJardinerosYaHub>): ParametrosJardinerosYaHub { return { ...parametrosVacios, ...input, comisionManejoPersonal: input?.comisionManejoPersonal?.length ? input.comisionManejoPersonal : comisionManejoPersonalInicial, trasladoBonoFinalizacion: input?.trasladoBonoFinalizacion?.length ? input.trasladoBonoFinalizacion : trasladoBonoFinalizacionInicial, mostrarEnWebPublica: Boolean(input?.mostrarEnWebPublica) }; }

const modulos: Array<{ valor: ModuloOperativoHub; etiqueta: string }> = [
  { valor: "jardinerosya", etiqueta: "JardinerosYa" },
  { valor: "fumigadoresya", etiqueta: "FumigadoresYa" },
  { valor: "comerciarya", etiqueta: "ComerciarYa" },
  { valor: "pileterosya", etiqueta: "PileterosYa" },
  { valor: "otro", etiqueta: "Otro" },
];

function numero(valor: string) { return Number(valor || 0); }

export function HubParametrosOperativosEditor({ hub }: { hub: HubPublico }) {
  const router = useRouter();
  const [moduloOperativo, setModuloOperativo] = useState<ModuloOperativoHub>(hub.moduloOperativo || "otro");
  const [parametros, setParametros] = useState(() => normalizarParametrosJardinerosYa(hub.parametrosOperativos?.jardinerosYa));
  const [nivelEstabilidad, setNivelEstabilidad] = useState(() => Math.min(10, Math.max(1, Math.round(Number(hub.nivelEstabilidad || 8)))));
  const [estado, setEstado] = useState("");

  async function guardar() {
    setEstado("Guardando parámetros operativos...");
    const respuesta = await fetch(`/api/hubs/${hub.slug}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ moduloOperativo, nivelEstabilidad, parametrosOperativos: { jardinerosYa: parametros } }) });
    if (respuesta.ok) { setEstado("Parámetros JardinerosYa del Hub guardados correctamente."); router.refresh(); return; }
    setEstado("No se pudieron guardar los parámetros operativos.");
  }

  return <section className="rounded-[2rem] border border-[#bfd3b8] bg-[#fbfdf8] p-6 shadow-sm">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-[#5d7032]">Parámetros operativos del Hub</p><h2 className="mt-1 text-2xl font-black">Parámetros operativos del Hub</h2><p className="mt-2 max-w-3xl text-sm font-semibold text-[#66745c]">Configurá las reglas económicas y operativas que usa este Hub para calcular reportes y organizar servicios.</p></div><button onClick={guardar} className="rounded-2xl bg-[#1f2a1d] px-4 py-3 text-sm font-black text-white">Guardar parámetros</button></div>
    <div className="mt-5 grid gap-3 md:grid-cols-2"><label className="grid gap-1 text-xs font-black uppercase text-[#66745c]">Módulo operativo del Hub<select value={moduloOperativo} onChange={(e) => setModuloOperativo(e.target.value as ModuloOperativoHub)} className="h-11 rounded-xl border border-[#cfd8c6] bg-white px-3 text-sm font-semibold normal-case outline-none">{modulos.map((modulo) => <option key={modulo.valor} value={modulo.valor}>{modulo.etiqueta}</option>)}</select></label><label className="grid gap-1 text-xs font-black uppercase text-[#66745c]">Nivel de estabilidad del Hub<input type="number" min="1" max="10" value={nivelEstabilidad} onChange={(e) => setNivelEstabilidad(Math.min(10, Math.max(1, Math.round(Number(e.target.value || 1)))))} className="h-11 rounded-xl border border-[#cfd8c6] bg-white px-3 text-sm font-semibold normal-case outline-none" /><span className="text-[11px] font-semibold normal-case text-[#66745c]">Valor manual de 1 a 10 visible en ficha, vista previa y mail.</span></label></div>
    {moduloOperativo === "jardinerosya" && <div className="mt-5 rounded-[1.5rem] border border-[#d8dfd1] bg-white p-4"><h3 className="text-xl font-black">Parámetros JardinerosYa del Hub</h3><p className="mt-2 text-sm font-semibold text-[#66745c]">Referencias para indicarle al jardinero cómo debería cobrar su día de trabajo dentro de este Hub.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><label className="grid gap-1 text-xs font-black uppercase text-[#66745c]">Precio de la hora de trabajo<input type="number" min="0" value={parametros.valorHoraTrabajo} onChange={(e) => setParametros((actual) => ({ ...actual, valorHoraTrabajo: numero(e.target.value) }))} className="h-10 rounded-xl border border-[#cfd8c6] px-3 text-sm font-semibold normal-case outline-none" /></label><label className="grid gap-1 text-xs font-black uppercase text-[#66745c]">Precio de la hora máquina bordeadora<input type="number" min="0" value={parametros.valorHoraBordeadora} onChange={(e) => setParametros((actual) => ({ ...actual, valorHoraBordeadora: numero(e.target.value) }))} className="h-10 rounded-xl border border-[#cfd8c6] px-3 text-sm font-semibold normal-case outline-none" /></label><label className="grid gap-1 text-xs font-black uppercase text-[#66745c]">Precio de la hora máquina de empuje<input type="number" min="0" value={parametros.valorHoraMaquinaEmpuje} onChange={(e) => setParametros((actual) => ({ ...actual, valorHoraMaquinaEmpuje: numero(e.target.value) }))} className="h-10 rounded-xl border border-[#cfd8c6] px-3 text-sm font-semibold normal-case outline-none" /></label></div><div className="mt-5 grid gap-4 xl:grid-cols-2"><RangosComision rangos={parametros.comisionManejoPersonal} onChange={(comisionManejoPersonal) => setParametros((actual) => ({ ...actual, comisionManejoPersonal }))} /><RangosTraslado rangos={parametros.trasladoBonoFinalizacion} onChange={(trasladoBonoFinalizacion) => setParametros((actual) => ({ ...actual, trasladoBonoFinalizacion }))} /></div></div>}
    <p className="mt-4 rounded-xl border border-[#d8dfd1] bg-white p-3 text-sm font-bold text-[#4f5f47]">JardinerosYa funciona como algoritmo operativo para Hubs de espacios verdes. La ficha del Hub define las reglas base del servicio.</p>{estado && <p className="mt-3 rounded-xl border border-[#cfe0c8] bg-[#eef7ea] px-3 py-2 text-sm font-black text-[#2f6d32]">{estado}</p>}
  </section>;
}

function RangosComision({ rangos, onChange }: { rangos: RangoComisionManejoPersonal[]; onChange: (rangos: RangoComisionManejoPersonal[]) => void }) { return <div className="rounded-2xl border border-[#d8dfd1] p-3"><div className="flex items-start justify-between gap-3"><div><h4 className="font-black">Comisión por manejo de personal</h4><p className="mt-1 text-xs font-semibold text-[#66745c]">A mayor cantidad de personas coordinadas, mayor comisión por manejo de personal.</p></div><button type="button" onClick={() => onChange([...rangos, { desde: 0, hasta: 0, porcentaje: 0 }])} className="rounded-xl border px-3 py-2 text-xs font-black">Agregar rango</button></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[560px] text-xs"><thead className="text-left uppercase text-[#66745c]"><tr><th className="p-2">Desde cantidad de ayudantes/personas</th><th className="p-2">Hasta cantidad de ayudantes/personas</th><th className="p-2">Porcentaje de comisión</th><th /></tr></thead><tbody>{rangos.map((rango, index) => <tr key={index}><td className="p-1"><input type="number" min="0" value={rango.desde} onChange={(e) => onChange(rangos.map((actual, i) => i === index ? { ...actual, desde: numero(e.target.value) } : actual))} className="h-9 w-full rounded-lg border px-2" /></td><td className="p-1"><input type="number" min="0" value={rango.hasta} onChange={(e) => onChange(rangos.map((actual, i) => i === index ? { ...actual, hasta: numero(e.target.value) } : actual))} className="h-9 w-full rounded-lg border px-2" /></td><td className="p-1"><input type="number" min="0" value={rango.porcentaje} onChange={(e) => onChange(rangos.map((actual, i) => i === index ? { ...actual, porcentaje: numero(e.target.value) } : actual))} className="h-9 w-full rounded-lg border px-2" /></td><td className="p-1 text-center"><button type="button" onClick={() => onChange(rangos.filter((_, i) => i !== index))} className="font-black text-[#743c3c]">×</button></td></tr>)}</tbody></table></div></div>; }

function RangosTraslado({ rangos, onChange }: { rangos: RangoTrasladoBonoFinalizacion[]; onChange: (rangos: RangoTrasladoBonoFinalizacion[]) => void }) { return <div className="rounded-2xl border border-[#d8dfd1] p-3"><div className="flex items-start justify-between gap-3"><div><h4 className="font-black">Traslado / bono de finalización</h4><p className="mt-1 text-xs font-semibold text-[#66745c]">A mayor cantidad de casas atendidas en una jornada, menor debería ser el costo de traslado por casa, incentivando finalizar y pasar a la siguiente casa.</p></div><button type="button" onClick={() => onChange([...rangos, { desde: 0, hasta: 0, valor: 0 }])} className="rounded-xl border px-3 py-2 text-xs font-black">Agregar rango</button></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[560px] text-xs"><thead className="text-left uppercase text-[#66745c]"><tr><th className="p-2">Desde cantidad de casas</th><th className="p-2">Hasta cantidad de casas</th><th className="p-2">Valor de traslado / bono de finalización</th><th /></tr></thead><tbody>{rangos.map((rango, index) => <tr key={index}><td className="p-1"><input type="number" min="0" value={rango.desde} onChange={(e) => onChange(rangos.map((actual, i) => i === index ? { ...actual, desde: numero(e.target.value) } : actual))} className="h-9 w-full rounded-lg border px-2" /></td><td className="p-1"><input type="number" min="0" value={rango.hasta} onChange={(e) => onChange(rangos.map((actual, i) => i === index ? { ...actual, hasta: numero(e.target.value) } : actual))} className="h-9 w-full rounded-lg border px-2" /></td><td className="p-1"><input type="number" min="0" value={rango.valor} onChange={(e) => onChange(rangos.map((actual, i) => i === index ? { ...actual, valor: numero(e.target.value) } : actual))} className="h-9 w-full rounded-lg border px-2" /></td><td className="p-1 text-center"><button type="button" onClick={() => onChange(rangos.filter((_, i) => i !== index))} className="font-black text-[#743c3c]">×</button></td></tr>)}</tbody></table></div></div>; }
